

services:
  # 1. Django Web Service
  web:
    build: .  # Build from the Dockerfile in this folder
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"  # Map your local port 8000 to container's 8000
    volumes:
      - .:/app  # Sync code changes for development
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - INTERNAL_API_BASE_URL=http://web:8000/api/v1
      - INTERNAL_HOST=web
      - DATABASE_HOST=db
      - DATABASE_NAME=notification_db
      - DATABASE_USER=victor
      - DATABASE_PASSWORD=secret123
    restart: unless-stopped

  # 2. Celery Worker Service
  worker:
    build: .
    command: celery -A core worker -l info -Q email,push
    volumes:
      - .:/app  # Sync code changes
    depends_on:
      - web
      - rabbitmq
    environment:
      - INTERNAL_HOST=web
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - DATABASE_HOST=db
      - DATABASE_NAME=notification_db
      - DATABASE_USER=victor
      - DATABASE_PASSWORD=secret123
    restart: unless-stopped

  # 3. RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # RabbitMQ management UI
      - "5672:5672"    # AMQP port
    restart: unless-stopped

  # 4. Redis Service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  # 5. Database Service (PostgreSQL)
  db:
    image: postgres:15
    container_name: core-db-1
    restart: unless-stopped
    environment:
      POSTGRES_USER: victor
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: notification_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: